# Generated by Django 4.0 on 2021-12-20 01:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VillageMoi1101007',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('villcode', models.CharField(blank=True, max_length=18, null=True)),
                ('countyname', models.CharField(blank=True, max_length=12, null=True)),
                ('townname', models.CharField(blank=True, max_length=12, null=True)),
                ('villname', models.CharField(blank=True, max_length=39, null=True)),
                ('villeng', models.CharField(blank=True, max_length=39, null=True)),
                ('countyid', models.CharField(blank=True, max_length=3, null=True)),
                ('countycode', models.CharField(blank=True, max_length=8, null=True)),
                ('townid', models.CharField(blank=True, max_length=8, null=True)),
                ('towncode', models.CharField(blank=True, max_length=12, null=True)),
                ('note', models.CharField(blank=True, max_length=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'village_moi_1101007',
                'managed': False,
            },
        ),
    ]
