# Generated by Django 4.0 on 2021-12-20 06:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('villcode', models.CharField(blank=True, max_length=18, null=True)),
                ('countyname', models.CharField(blank=True, max_length=12, null=True)),
                ('townname', models.CharField(blank=True, max_length=12, null=True)),
                ('villname', models.CharField(blank=True, max_length=39, null=True)),
                ('villeng', models.CharField(blank=True, max_length=39, null=True)),
                ('countyid', models.CharField(blank=True, max_length=3, null=True)),
                ('countycode', models.CharField(blank=True, max_length=8, null=True)),
                ('townid', models.CharField(blank=True, max_length=8, null=True)),
                ('towncode', models.CharField(blank=True, max_length=12, null=True)),
                ('note', models.CharField(blank=True, max_length=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'map_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('field_gid', models.FloatField(blank=True, db_column='__gid', null=True)),
                ('markid', models.CharField(blank=True, max_length=11, null=True)),
                ('marktype1', models.CharField(blank=True, max_length=8, null=True)),
                ('marktype2', models.CharField(blank=True, max_length=8, null=True)),
                ('markname1', models.CharField(blank=True, max_length=254, null=True)),
                ('markname2', models.CharField(blank=True, max_length=254, null=True)),
                ('mdate', models.CharField(blank=True, max_length=8, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=35, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'station_4326',
                'managed': False,
            },
        ),
    ]
